account/urls.py
from django.urls import path
from account import views as v

urlpatterns = [
    path("Reg",v.reg,name="reg"),
    path("Login",v.logi,name="loginpage"),
    path("Logout",v.logt,name="logout"),
    
    path("edit/<int:id>",v.edit,name="edit"),

    path("collections",v.collections,name="collections"),
    path("products/<str:slug>",v.productsview,name="productsview"),
    path("product/<str:cate_slug>/<str:prod_slug>",v.productview,name="productview"),

    path('add-to-cart',v.addtocart,name="addtocart"),
    path('cart',v.viewcart, name="cart"),
    path("deletecart/<int:id>",v.deletecart,name="deletecart"),
    path("update-cart",v.updatecart,name="updatecart"),

    path('add-to-wishlist',v.addtowishlist,name="addtowishlist"),
    
    path("wishlist",v.wishlist,name="wishlist"),
    path("deletewishlist/<int:id>",v.deletewishlist,name="deletewishlist"),
    path("checkout",v.checkoutview,name="checkout"),
    path('place-order',v.placeorder,name="placeorder"),

    path("my-orders", v.myorders,name="myorders"),
    path("view-order/<str:t_no>",v.vieworder,name="orderview"),

    path('proceed-to-pay',v.razorpaycheck)

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from account import urls as ua

from account.views import home
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",home),
    path("ACCOUNT-",include((ua,"account") ,namespace="acc")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms

class Category(models.Model):
    slug=models.CharField(max_length=150)
    name=models.CharField(max_length=150)
    image=models.ImageField(upload_to="myimages")
    description=models.TextField(max_length=500)
    status=models.BooleanField(default=False,help_text="0-default,1-hidden")

    def __str__(self):
        return self.name
    
    class Meta:
        db_table="category"
    
class Product(models.Model):
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    slug=models.CharField(max_length=150)
    name=models.CharField(max_length=150)
    product_image=models.ImageField(upload_to="myimages")
    small_description=models.TextField(max_length=250) 
    status=models.BooleanField(default=False,help_text="0-default,1-hidden")
    trending=models.BooleanField(default=False,help_text="0-default,1-hidden")
    quantity=models.IntegerField()
    description=models.TextField(max_length=500)
    original_price=models.IntegerField()
    selling_price=models.IntegerField()

    def __str__(self):
        return self.name
    
    class Meta:
        db_table="product"

class Cart(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    product_qty = models.IntegerField()

    def __str__(self):
        return self.product

class Wishlist(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.product

class Order(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    fname=models.CharField(max_length=100, null=False)
    lname=models.CharField(max_length=100, null=False)
    email=models.CharField(max_length=100, null=False)
    phone=models.CharField(max_length=100, null=False)
    address=models.TextField(null=False)
    city=models.CharField(max_length=100, null=False)
    state=models.CharField(max_length=100, null=False)
    country=models.CharField(max_length=100, null=False)
    pincode=models.CharField(max_length=100, null=False)
    total_price=models.FloatField(null=False)
    payment_mode=models.CharField(max_length=150, null=False)
    payment_id=models.CharField(max_length=250,null=True)
    orderstatuses = (
        ('pending','pending'),
        ('Out for shipping','Out for shipping'),
        ('Completed','Completed')
    )
    status=models.CharField(max_length=150,choices=orderstatuses, default='Pending')
    message=models.TextField(null=True)
    tracking_no = models.CharField(max_length=150, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.id, self.tracking_no)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    price = models.FloatField(null=False)
    quantity = models.IntegerField(null=False)

    def __str__(self):
        return '{} - {}'.format(self.order.id, self.order.tracking_no)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=50,null=False)
    address=models.TextField(null=False)
    city=models.CharField(max_length=100, null=False)
    state=models.CharField(max_length=100, null=False)
    country=models.CharField(max_length=100, null=False)
    pincode=models.CharField(max_length=100, null=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username














class RegForm(UserCreationForm):
    class Meta:
        model=User
        fields=("first_name","last_name","email","username")
        widgets={
            "first_name" : forms.TextInput(attrs={'class':'form-control'}),
            "last_name" : forms.TextInput(attrs={'class':'form-control'}),
            "email" : forms.EmailInput(attrs={'class':'form-control'}),
            "username" : forms.TextInput(attrs={'class':'form-control'}),
        }

class LoginForm(forms.Form):
    username=forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'form-control w-75 m-1 p-1'}))
    password=forms.CharField(max_length=35,widget=forms.PasswordInput(attrs={'class':'form-control w-75 m-1'}))
   

account/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from account.models import *
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
import random

def home(request):
    trending_products=Product.objects.filter(trending=1)
    d={'trending_products':trending_products}
    return render(request,"home.html",d)


def reg(request):
    if request.method == "POST":
        obj = RegForm(request.POST)
        obj.save()
        messages.success(
            request, "Your account has been successfully created...!!")
        return redirect("/ACCOUNT-Login")
    else:
        d = {"form": RegForm}
        return render(request, "register.html", d)


def logi(request):
    if request.method == "POST":
        uname = request.POST.get("username")
        passw = request.POST.get("password")
        user = authenticate(request, username=uname, password=passw)
        if user is not None:
            request.session["uid"] = user.id
            login(request, user)
            messages.success(request, "Logged In Successfully..!!!")
            return redirect("/")
        else:
            messages.error(request, "Invalid username & password..!!!")
            return redirect("/ACCOUNT-Login")
    else:
        d = {"form": LoginForm}
        return render(request, "login.html", d)


def logt(request):
    logout(request)
    messages.success(request, "Logged Out successfully...!!!")
    return redirect("/")


def collections(request):
    category = Category.objects.all
    return render(request, "collection.html", {'category': category})


def productsview(request, slug):
    if (Category.objects.filter(slug=slug)):
        products = Product.objects.filter(category__slug=slug)
        category = Category.objects.filter(slug=slug).first()
        d = {"products": products, "category": category}
        return render(request, "products.html", d)
    else:
        messages.warning(request, "No such category found")
        return redirect("/ACCOUNT-collections")


def productview(request, cate_slug, prod_slug):
    if (Category.objects.filter(slug=cate_slug)):
        if (Product.objects.filter(slug=prod_slug)):
            products = Product.objects.filter(slug=prod_slug).first()
            d = {"products": products}
        else:
            messages.error(request, "No such Product found")
            return redirect("/ACCOUNT-collections")
    else:
        messages.error(request, "No such category found")
        return redirect("/ACCOUNT-collections")
    return render(request, "productview.html", d)


def addtocart(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            prod_id = int(request.POST.get('product_id'))
            product_check = Product.objects.get(id=prod_id)
            if (product_check):
                if (Cart.objects.filter(user=request.user.id, product_id=prod_id)):
                    
                    return JsonResponse({'status': "Product already in cart"})
                else:
                    prod_qty = int(request.POST.get('product_qty'))

                    if product_check.quantity >= prod_qty:
                        Cart.objects.create(user=request.user, product_id=prod_id, product_qty=prod_qty)
                        return JsonResponse({'status': "Product added successfully"})
                    else:
                        return JsonResponse({'status': "Only "+str(product_check.quantity) + " quantity available"})
            else:
                return JsonResponse({'status': "No such product found"})
        else:
            return JsonResponse({'status': "Login to Continue"})
    return redirect("/")

def addtowishlist(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            prod_id = int(request.POST.get('product_id'))
            product_check = Product.objects.get(id=prod_id)
            if (product_check):
                if (Wishlist.objects.filter(user=request.user, product_id=prod_id)):                   
                    return JsonResponse({'status': "Product already in wishlist"})
                else:
                    Wishlist.objects.create(user=request.user, product_id=prod_id)
                    return JsonResponse({'status': "Product added to wishlist"})
            else:
                return JsonResponse({'status': "No such product found"})
        else:
            return JsonResponse({'status': "Login to Continue"})
    return redirect("/")

def viewcart(request):
    cart = Cart.objects.filter(user=request.user)
    d = {'cart': cart}
    return render(request, "cart.html", d)


def deletecart(request, id):
    obj = Cart.objects.get(id=id)
    obj.delete()
    return redirect("/ACCOUNT-cart")


def edit(request, id):
    user = User.objects.get(id=id)
    if request.method == "POST":
        obj = RegForm(request.POST, instance=user)
        obj.save()
        messages.success(
            request, "Your profile has been successfully updated...!!!")
        return redirect("/")
    else:
        x = RegForm(instance=user)
        d = {"form": x}
        return render(request, "edituser.html", d)

def updatecart(request):
    if request.method == 'POST':
        prod_id = int(request.POST.get('product_id'))
        if(Cart.objects.filter(user=request.user, product_id=prod_id)):
            prod_qty = int(request.POST.get('product_qty'))
            cart = Cart.objects.get(product_id=prod_id, user=request.user)
            cart.product_qty = prod_qty
            cart.save()
            return JsonResponse({'status':"Updated successfully"})
    return redirect("/")

def wishlist(request):
    wishlist=Wishlist.objects.filter(user=request.user)
    d={'wishlist':wishlist}
    return render(request,"wishlist.html",d)

def deletewishlist(request, id):
    obj = Wishlist.objects.get(id=id)
    obj.delete()
    return redirect("/ACCOUNT-wishlist")


def checkoutview(request):
    rawcart=Cart.objects.filter(user=request.user)
    for item in rawcart:
        if item.product_qty > item.product.quantity:
            abc = Cart.objects.get(id=item.id)
            abc.delete()

    cartitems = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cartitems:
        total_price = total_price + item.product.selling_price * item.product_qty

    userprofile = Profile.objects.filter(user=request.user).first()

    d={'cartitems': cartitems, 'total_price':total_price,"userprofile":userprofile}
    return render(request, "checkout.html",d)

def placeorder(request):
    if request.method == 'POST':

        currentuser = User.objects.filter(id=request.user.id).first()

        if not currentuser.first_name:
            currentuser.first_name = request.POST.get('fname')
            currentuser.last_name = request.POST.get('lname')
            currentuser.save()

        if not Profile.objects.filter(user=request.user):
            userprofile = Profile()
            userprofile.user = request.user   
            userprofile.phone = request.POST.get('phone')
            userprofile.address = request.POST.get('address')
            userprofile.city = request.POST.get('city')
            userprofile.state = request.POST.get('state')
            userprofile.country = request.POST.get('country')
            userprofile.pincode = request.POST.get('pincode')
            userprofile.save()

        neworder = Order()
        neworder.user = request.user
        neworder.fname = request.POST.get('fname')
        neworder.lname = request.POST.get('lname')
        neworder.email = request.POST.get('email')
        neworder.phone = request.POST.get('phone')
        neworder.address = request.POST.get('address')
        neworder.city = request.POST.get('city')
        neworder.state = request.POST.get('state')
        neworder.country = request.POST.get('country')
        neworder.pincode = request.POST.get('pincode')

        neworder.payment_mode = request.POST.get('payment_mode')
        cart=Cart.objects.filter(user=request.user)
        cart_total_price = 0
        for item in cart:
            cart_total_price = cart_total_price + item.product.selling_price * item.product_qty

        neworder.total_price = cart_total_price
        trackno = 'BRO'+str(random.randint(1111111,99999999))
        while Order.objects.filter(tracking_no=trackno) is None:
            trackno = 'BRO'+str(random.randint(1111111,99999999))

        neworder.tracking_no = trackno
        neworder.save()

        neworderitems = Cart.objects.filter(user=request.user)
        for item in neworderitems:
            OrderItem.objects.create(
                order=neworder,
                product=item.product,
                price=item.product.selling_price,
                quantity=item.product_qty
            )

            orderproduct = Product.objects.filter(id=item.product_id).first()
            orderproduct.quantity = orderproduct.quantity - item.product_qty
            orderproduct.save()

        Cart.objects.filter(user=request.user).delete()

        messages.success(request, "Your order has been placed successfully")

    return redirect('/')

def myorders(request):
    orders = Order.objects.filter(user=request.user)
    d={'orders':orders}
    return render(request,"orders.html",d)

def vieworder(request, t_no):
    order = Order.objects.filter(tracking_no=t_no).filter(user=request.user).first()
    orderitems = OrderItem.objects.filter(order=order)
    d={'order':order,'orderitems':orderitems}
    return render(request,"vieworder.html",d)

def razorpaycheck(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cart:
        total_price = total_price + item.product.selling_price * item.product_qty

    return JsonResponse({
        'total_price': total_price
    })

account/templates/checkout.html
{% extends "master.html" %}
{%load static%}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    <link rel="stylesheet" href="{%static 'css/manual.css'%}">
    <!-- <script src="{%static 'js/jquery-3.6.3.min.js'%}"></script> -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <!-- Default theme -->
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


<body style="background-color: black;">
{% block "body" %}

<div class="container mt-5">
    <form action="{% url 'acc:placeorder' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-7">
                <div class="card ">
                    <div class="card-body">
                        <h6>Basic Details</h6>
                        <hr>
                        <div class="row checkoutform">
                            <div class="col-md-6">
                                <label for="">First Name</label>
                                <input type="text" class="form-control" value="{{ request.user.first_name }}" name="fname" placeholder="Enter first name"
                                    required>
                            </div>
                            <div class="col-md-6">
                                <label for="">Last Name</label>
                                <input type="text" class="form-control" value="{{ request.user.last_name }}" name="lname" placeholder="Enter last name"
                                    required>
                            </div>
                            <div class="col-md-6 mt-2">
                                <label for="">Email</label>
                                <input type="email" class="form-control" name="email" value="{{ request.user.email }}" placeholder="Enter Email"
                                    required>
                            </div>
                            <div class="col-md-6 mt-2">
                                <label for="">Phone</label>
                                <input type="text" class="form-control" name="phone" value="{{ userprofile.phone }}" placeholder="Enter Phone" required>
                            </div>
                            <div class="col-md-12 mt-2">
                                <label for="">Address</label>
                                <textarea class="form-control" placeholder="Enter " name="address" required>{{ userprofile.address }}</textarea>
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="">City</label>
                            <input type="text" class="form-control" placeholder="Enter City" name="city" value="{{ userprofile.city }}" required>
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="">State</label>
                            <input type="text" class="form-control" placeholder="Enter State" name="state" value="{{ userprofile.state }}"  required>
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="">Country</label>
                            <input type="text" class="form-control" placeholder="Enter Country" name="country" value="{{ userprofile.country }}"  required>
                        </div>
                        <div class="col-md-6 mt-2">
                            <label for="">Pin Code</label>
                            <input type="text" class="form-control" placeholder="Enter Pin Code" name="pincode" value="{{ userprofile.pincode }}"  required>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <div class="card shadow shadow-secondary ">
                <div class="card-body ">
                    <h6>Order Summary</h6>
                    <hr>
                    {% if cartitems %} 
                        <table class="table table-stripeds table-bordereds">
                            <thead>
                                <tr>
                                    <th>Product</th>
                                    <th>Quantity</th>
                                    <th>Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cartitems %} 
                                    <tr>
                                        <td>
                                            <img src="{{ item.product.product_image.url }}" height="50px" class="me-2" width="50px" alt="">
                                            {{ item.product.name }}</td>
                                        <td>{{ item.product_qty }}</td>
                                        <td>{{ item.product.selling_price }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <h6>Grand Total
                            <span class="float-end">Rs {{ total_price }}</span>
                        </h6>
                        <input type="hidden" value="COD" name="payment_mode">
                        <div class="mt-3">
                            <button type="submit" class="btn btn-success w-100"> COD | Place Order </button>
                            <button type="button" class="btn btn-primary payWithRazorpay w-100 mt-2"> COD | Pay with Razorpay</button>
                        </div>
                    {% else %} 
                        <h4>your cart is empty</h4>
                    {% endif %}
                </div>
            </div>        
        </div>
    </div>
</form>
</div><br><br><br>
{% endblock %}

{% load static %}
<script src="{% static '/js/jquery-3.6.3.min.js' %}"></script>
<script src="{% static '/js/custom.js' %}"></script>
<script src="{%static '/js/main.js'%}"></script>
<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

{% block scripts %} 
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock scripts %}
<script src="{%static '/js/checkout.js'%}"></script>

</body>

account/templates/edituser.html
{%extends "master.html"%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit profile</title>
    <style>
        
    </style>
</head>

<body>
    {% block "body" %}

    <div class="container mt-3">
        <form action="" method="post">
            {% csrf_token %}
            <table  class="table text-light table-borderless border border-danger rounded">
                {{form.as_table}}
                <tr class="text-center">
                    <td><input type="submit" class="btn btn-outline-success "></td>
                    <td><input type="reset" class="btn btn-outline-primary"></td>
                </tr>
            </table>
        </form>
    </div>
    {% endblock %}
</body>

</html>

account/templates/navbar.html
{%load static%}

<link rel="stylesheet" href="{%static 'css/main.css'%}">
<link rel="stylesheet" href="{%static 'css/manual.css'%}">
<style>
    .box:before {
        content: "";
        z-index: -1;
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: linear-gradient(-179deg, red 0%, #000000 100%);
        transform: translate3d(0px, 20px, 0) scale(0.95);
        filter: blur(20px);
        opacity: var(0.7);
        transition: opacity 0.3s;
        border-radius: inherit;
    }



    /* 
    * Prevents issues when the parent creates a 
    * stacking context. (For example, using the transform
    * property )
    */
    .box::after {
        content: "";
        z-index: -1;
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        background: inherit;
        border-radius: inherit;
    }
</style>

<nav class="navbar navbar-expand-lg box" id="arrowup" style="background-color: black; margin-bottom: 0px; padding-bottom: 0px;">
    <div class="container-fluid">
        <a class="navbar-brand ms-3" href="#">
            {%load static%}
            <img src="static/images/brologo.jpg" alt="logo" width="130" height="64">
        </a>

        <div class="collapse navbar-collapse ms-3" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-1 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/"
                        style="color: red; font-size: 20px;">Home</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link px-4" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"
                        style="color: red; font-size: 20px;">
                        Men's wear
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'acc:collections' %}">Categories</a></li>
                        <!-- <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li> -->
                    </ul>
                </li>

                <li class="nav-item">
                    <a class="nav-link px-3 disabled" style="color: red; font-size: 20px;">Accessories</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link px-3" href="#testimonial" style="color: red; font-size: 20px;">AboutUs</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#contact" style="color: red; font-size: 20px;">ContactUs</a>
                </li>
            </ul>
            <form class="d-flex px-4" role="search">
                <button class="btn btn-dark" type="submit">
                    <i class="fa fa-search"></i>
                </button>
                <input class="form-control border-dark" type="search" placeholder="Search" aria-label="Search"
                    style="background-color: #1a1918;">
            </form>
            <ul class="navbar-nav ms-3">
                <li class="nav-item dropdown">
                    <a href="{% url 'acc:reg' %}" style="text-decoration: none; color:red;"></a>
                    <i class="fa fa-user-circle-o mx-4 fs-5" aria-hidden="true" style="color: red;"></i>
                    <h6>
                        <label style="color: red;" class="nav-link mt-1 pt-1" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <h6 width="50" height="3">profile</h6>
                        </label>

                        <ul class="dropdown-menu ">
                            {% if user.is_authenticated %}
                            <li><a class="dropdown-item fw-semibold" href="{% url 'acc:myorders' %}">My orders</a></li>
                            <li><a class="dropdown-item fw-semibold" href="{% url 'acc:edit' user.id %}">Edit Profile</a></li>
                            <li><a class="dropdown-item text-danger fw-semibold" href="{% url 'acc:logout' %}">LOGOUT</a></li>
                            
                            {% else %}
                            <li><a class="dropdown-item fw-semibold" href="{% url 'acc:loginpage' %}">LOGIN</a></li>

                            <li><a class="dropdown-item fw-semibold" href="{% url 'acc:reg' %}">Create New Account</a></li>
                            {% endif %}
                        </ul>
                    </h6>
                </li>

                <li class="nav-item">

                    <a href="{% url 'acc:cart' %}"><i class="fa fa-shopping-cart fs-5 mx-1" width="22" height="30" style="color: red;" aria-hidden="true"></i>
                    <br>
                    <label style="color: red;" class="mt-1 pt-0">
                        <h6 width="50" height="3" class="fs-6">cart</h6>
                    </label>
                </a>
                </li>

                <li class="nav-item">

                <a href="{% url 'acc:wishlist' %}">
                    <i class="fa fa-heart mx-4" aria-hidden="true" style="color: red;"></i>
                    <br>
                    <label style="color: red;"  class="mt-1 pt-0">
                        <h6 width="50" height="3">&nbsp;&nbsp;wishlist</h6>
                    </label>
                </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

account/templates/wishlist.html
{%extends "master.html"%} 

{% block "body" %}

<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card shadow ">
                    <div class="card-body">
                        {% if wishlist %} 
                            {% for i in wishlist %} 
                            <div class="row product_data mb-1">
                                <div class="col-md-2 my-auto">
                                    <img src="{{ i.product.product_image.url}}" height="70px" width="70px"  alt="">
                                </div>
                                <div class="col-md-3 my-auto">
                                    <h6>{{i.product.name}}</h6>
                                </div>
                                <div class="col-md-2 my-auto">
                                    <h6> Rs {{i.product.selling_price }}</h6>
                                </div>
                                

                                <div class="col-md-3 my-auto">
                                    <input type="hidden" class="prod_id" value="{{ i.product_id }}">
                                    {% csrf_token %} 
                                    <a href="{% url 'acc:productview' i.product.category.slug i.product.slug %}" class="btn btn-primary"> View Product </a>
                                </div>

                                <div class="col-md-2 my-auto">
        
                                    <a href="{% url 'acc:deletewishlist' i.id %}" class="btn btn-danger">Remove <i class="fa fa-trash"></i></a>
                                </div>
                            </div>
                
                            {% endfor %}
                            <a href="{% url 'acc:checkout' %}" class="btn btn-outline-success float-end">Checkout</a>
                        {% else %}
                            <h4>Your wishlist is empty</h4>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br><br><br><br><br>
<br><br><br>


{% endblock %}

{% block scripts %}

{% endblock scripts %}